name: JoltItems
version: 1.0
author: JoltTheBolt
main: io.github.JoltMuz.joltitems.Main
api-version: Spigot-1.8.8-R0.1-SNAPSHOT-latest

commands:
  joltitems:
    description: All JoltItems.
    usage: /joltitems
